### ISSUE TITLE
Derive a code enum for Multihash

### ISSUE THREAD

**Issue by dvc94ch** [ipfs-rust/tiny-multihash#12]

**Comment by vmx** [comment]
Is the idea of a code enum to be able to do things like `Code::SHA2_256::digest(b"inputdata")` which returns the digest and never errors (as opposed to `Multihash::new(SHA2_256, b"inputdata")` which might fail if `SHA2_256` isn't a supported codec)?

**Comment by dvc94ch** [comment]
Yes, it also allows using Code as a generic type param.

**Comment by vmx** [comment]
K, cool. I'll have a look at it.

**Comment by vmx** [comment]
I'm almost done. I ended up doing a bigger change which makes things generally simpler. I'm already in the cleaning up the code, make sure *everything* still works phase.
