### ISSUE TITLE
Custom code table doesn't work

### ISSUE THREAD

**Issue by vmx** [ipfs-rust/tiny-multihash#15]
I tried to use a custom code table and it doesn't compile. I don't fully get what the problem is, it seems to be related to the derive. Perhaps it's outdated?

Steps to reproduce:

```console
$ cargo init bug
$ cd bug
$ cp <path-to-tiny-myltihash>/tests/custom_table.rs src/main.rs
$ cargo add tiny-multihash
$ cargo build
```

Error (besides missing `main()`) is

```
error[E0046]: not all trait items implemented, missing: `read`
 --> src/main.rs:7:28
  |
7 | #[derive(Clone, Debug, Eq, Multihash, PartialEq)]
  |                            ^^^^^^^^^ missing `read` in implementation
  |
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
  = help: implement the missing item: `fn read<R, Self>(_: R) -> std::result::Result<Self, tiny_multihash::Error> where R: std::io::Read { todo!() }`
```

**Comment by dvc94ch** [comment]
You need to add the std feature flag, we discussed it multiple times already

**Comment by vmx** [comment]
Oh sorry. I tried that. let me try it again.

**Comment by vmx** [comment]
In my Cargo.toml I have

```
[dependencies]
tiny-multihash = { version = "0.4.4", features = ["std"]}
```

Also tiny-multihash also has `std` by default: https://github.com/ipfs-rust/tiny-multihash/blob/af0478e80017c3fc8780fdb552079d632364781b/Cargo.toml#L17

Do I need to do anything special if I use the derive macro?

**Comment by vmx** [comment]
Sorry https://github.com/ipfs-rust/tiny-multihash/issues/6#issuecomment-668560921

**Comment by vmx** [comment]
I'll add this to the documentation now. so it doesn't trip me up again.
