### ISSUE TITLE
Strobe hasher doesn't assigned Multicodec code

### ISSUE THREAD

**Issue by vmx** [ipfs-rust/tiny-multihash#21]
Currently this library is using `0xa0` and `0xa1` for [Strobe hashing](https://strobe.sourceforge.io/specs/). Though those are not yet part of the [Multicodec table](https://github.com/multiformats/multicodec/blob/e0e95825a0ec85e4f63ea2771df700d92a80523e/table.csv).

We can either get Strobe added to the Multicodec table with opening an issue there, which might take a while. From a quick look it's not quite clear to me how many variants exists and which ones one might want to have in the Multicodec table and how to describe/name them there.

Or we make it a hasher that's not included by default, hence doesn't have a Multicodec code.

**Comment by dvc94ch** [comment]
That's fine. Benchmarking shows it's very slow, 5us on my laptop. The only advantage would be code size for embedded systems. Let's hope the next gen intel cpu's have a built in strobe hardware accelerator, that would be cool.

**Comment by vmx** [comment]
So we just move it out of the default table (that would be the easier than assigning a Multicodec code to it)?

**Comment by dvc94ch** [comment]
Yep, why not
