### ISSUE TITLE
Add BLAKE3 support

### ISSUE THREAD

**Issue by vmx** [ipfs-rust/tiny-multihash#22]
BLAKE3 was [recently added to rust-multihash](https://github.com/multiformats/rust-multihash/pull/74). I'd like to add support here too before merging things upstream (so that we are closer to feature parity before the merge).

**Comment by mriise** [comment]
ill try and get to this soon.

**Comment by mriise** [comment]
i've started with a fork now. I may open a PR before i completely finish to make sure im doing things properly.

**Comment by vmx** [comment]
Thanks for the heads up. It's been on my list for this week, but it's great to get such a contribution. I'm looking forward to review your code!

**Comment by vmx** [comment]
@mriise Any news? I think I added all features to get it to feature parity with the current rust-multihash. Only BLAKE3 support is missing.

There is no time preasure. BLAKE3 support can even be added after the merge (before the release). Also things will still take a while. E.g.. rust-cid needs to be updated and I also want to try things out with other users like libp2p before doing an actual release.

**Comment by vmx** [comment]
@mriise I will probably look into this next week.

**Comment by vmx** [comment]
@mriise Please also note that in case you're working on it, https://github.com/ipfs-rust/tiny-multihash/pull/34 changes this libarry quite a bit (though the hashing code should still be pretty similar).

**Comment by mriise** [comment]
Thanks for the heads up. I'll give it another shot, I stopped midway since i was having problems with rustc not recognizing the feature flag for blake3 (i'm sure i missed something somewhere)

If you don't mind taking a look at it to see what i'm missing, I'll open a PR for it after I refactor for #34
