### ISSUE TITLE
Allow selection of hashing algorithm with a string name as well as a u64 code

### ISSUE THREAD

**Issue by grenewode** [ipfs-rust/tiny-multihash#32]
I am looking at using this library in an application. For my usecase, I would like users to be algorithm to specify which hashing algorithm they would like to use. I could allow them to enter the corresponding numeric code, but that isn't very friendly. Alternatively, I could write my own simple converter that takes `str` names such as "sha2_256" to `u64` codes, but that seems tedious and error prone. 

Also, if #12 is implemented, then this could be easily be achieved by auto generating implementations for `FromStr` and `TryFrom<u64>` for the `Code` enum. This would likely require the addition of a `name` parameter, similar to `#[mh(code=..., ...)` that would allow the developer to specify a custom name for hash functions.

Some additional ideas:
* Allow an `aliases` parameter, allowing multiple names for a hash functions (this may help with cases where a hash function has multiple common names, or in cases where  translation/internationalization is necessary).
* If the `enum Code` based implementation is used, then it would be very nice to have at least `serde::Deserialize` implementation for `Code` that can translate a `u64` value or a `str` value. This will enable developers to add hash function selection to configuration files or cli interfaces easily.
* Another very useful feature (although more complicated to implement nicely) would be to have some way to enumerate all the variants of a `Code` enum, so that developers can easily list supported hash functions without violating DRY, as well as enabling `found X but expected one of Y1, Y2, Y3, ...` errors. However, I'm not sure if this is a good idea. You could report just the names - but then how would you report aliases? If you report names, should you report codes as well? What do you actually report? An iterator (but that would mean having an `IterVariants` associated type...)? An array (but then adding a new hashing algorithm would increase the size, which would be breaking change...)? A static slice? Also, this kind of "what are all the things" doesn't seem to be very common in the rust ecosystem, especially for performance-oriented crates like this one, so it might be surprising for developers.

**Comment by vmx** [comment]
String names sounds application specific to me. As you mention, sometimes it might even make sense to map several different strings to the same name. I guess I would put that into the application logic instead.
